name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile
        run: |
          g++ main.cpp problem1.cpp problem2.cpp problem3.cpp problem4.cpp \
            -o hw2_main -std=c++17

      - name: Test Case 1
        id: test1
        uses: education/autograding-command-grader@v1
        with:
          test-name: Test Case 1
          setup-command: ''
          command: bash -c './hw2_main Test/case1.txt | diff - Test/expected1.txt'
          timeout: 10
          max-score: 33

      - name: Test Case 2
        id: test2
        uses: education/autograding-command-grader@v1
        with:
          test-name: Test Case 2
          setup-command: ''
          command: bash -c './hw2_main Test/case2.txt | diff - Test/expected2.txt'
          timeout: 10
          max-score: 33

      - name: Test Case 3
        id: test3
        uses: education/autograding-command-grader@v1
        with:
          test-name: Test Case 3
          setup-command: ''
          command: bash -c './hw2_main Test/case3.txt | diff - Test/expected3.txt'
          timeout: 10
          max-score: 34

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          TEST1_RESULTS: "${{steps.test1.outputs.result}}"
          TEST2_RESULTS: "${{steps.test2.outputs.result}}"
          TEST3_RESULTS: "${{steps.test3.outputs.result}}"
        with:
          runners: test1,test2,test3
